### PR TITLE
[Merged by Bors] - ci: revert orb version (IN-000)

### PR DESCRIPTION
**Pull request by Xavientois**
Reverts back to a released version of the orb

### CODE REVIEW

**Comment by xavidop** [comment]
why are you reverting back?

**Comment by Xavientois** [comment]
@xavidop To end the test for today. I don't want to have issues with the CI while I sleep tonight

**Review by xavidop — APPROVED** [review]
Perfect

**Comment by Xavientois** [comment]
bors merge

**Pull request closed without merging**
