### PR TITLE
[Merged by Bors] - test(ci): try refactored orb (IN-304)

### PR DESCRIPTION
**Pull request by Xavientois**
**Fixes or implements IN-304**

### Brief description. What is this change?

This will point to the dev release for the refactored vfcommon orb. All functionality should be identical to before, the code has just been refactored to follow the latest patterns in orb development.

### Implementation details. How do you make this change?

All orb components have been separated into individual files and shell scripts have been extracted for better maintainability and testing.

### Related PRs

- https://github.com/voiceflow/google-service/pull/291
- https://github.com/voiceflow/orb-common/pull/82

### CODE REVIEW

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Review by frankgu968 — COMMENTED** [review]
What does this change accomplish? seems to be just publishing a dev version + some whitespace changes

**Review by frankgu968 — APPROVED** [review]

**Comment by Xavientois** [comment]
bors merge

**Pull request closed without merging**
